### ISSUE TITLE
SSG detail view: Expand Manuscript information

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#216]
In the Manuscript table in the SSG detail view, the user should be able to "expand" each column of the table with the manuscript records with a button close to the abbreviated name of the field that belongs to the column. This way the user can make selections on what to make visible and what not. 

The current fields should be replaced by these: 

1. Shelfmark
2. Origin/Provenance (abbrev. or./prov.)
3. Date range (abbrev. date)
4. Collection name (abbrev. coll.)
5. Item (6/128) (abbrev. item)
6. Folio number of item (abbrev. ff.)
7. Attributed author (abbrev. auth.)
8. Incipit (abbrev. inc.)
9. Explicit (abbrev. expl.)
10. Keywords of the SermDescr (abbrev. keyw.)

Only the shelfmark should be always fully visible. The field names of the other columns should be abbreviated when not expanded. In the abbreviated status, an arrow next to each field name should be visible. With this arrow the user can expand the specific column to show the (complete) contents of that column. The user should expand multiple columns without influencing the legibility of the expandend columns.

The aim is to better compare the manuscripts.

**Comment by shariboodts** [comment]
I've discussed this with Thijs and we have come up with a slightly different visualisation. Instead of a row below each manuscript, we would keep all manuscript information on one row, but allow the user to expand the columns containing each type of information. This has the advantage that information for each manuscript can be easily compared with the same type of information in the other manuscripts in the list.

Order of the columns should be, from left to right:
1. Shelfmark
2. Origin/Provenance (abbrev. or./prov.)
3. Date range (abbrev. date)
4. Collection name (abbrev. coll.)
5. Item (6/128) (abbrev. item)
6. Folio number of item (abbrev. ff.)
7. Attributed author (abbrev. auth.)
8. Incipit (abbrev. inc.)
9. Explicit (abbrev. expl.)
10. Keywords of the SermDescr (abbrev. keyw.)

Default expanded should only the manuscript's shelfmark. Of all other categories/columns you should see only the abbrev. name at the top of the list with a small arrow next to it, allowing you to expand that column for all manuscripts in the list at once. You should be able to expand multiple columns without automatically compressing (I don't know the technical term) others. But, I can imagine there is a limit to this, given page width. If necessary, we can discuss this further.

**Comment by ErwinKomen** [comment]
The column contents is either Manuscript ('M') or Sermon specific ('S'):

1. **M** Shelfmark
2. **M** Origin/Provenance (abbrev. or./prov.)
3. **M** Date range (abbrev. date)
4. **????** Collection name (abbrev. coll.)
5. **S** Item (6/128) (abbrev. item)
6. **S** Folio number of item (abbrev. ff.)
7. **S** Attributed author (abbrev. auth.)
8. **S** Incipit (abbrev. inc.)
9. **S** Explicit (abbrev. expl.)
10. **S** Keywords of the SermDescr (abbrev. keyw.)

**Comment by shariboodts** [comment]
4. M Collection name (referring to the historical collection or collections present (perhaps with some variations) in this manuscript)

PS Riccardo, Iris, and I will discuss the collection environment, features, definitions at length next week. From that will come a better understanding of this concept in the database and a list of issues relating to it.

**Comment by ErwinKomen** [comment]
Okay, please have a look at my attempt to facilitate 'resizable columns for the list of sermon manifestations associated with a SSG'.

Features:
1. The 'Shelfmark' column is full-size initially, the other columns are as small as the column header
1. Clicking a column header expands or reduces the width of that column again
1. The size of each column can be adapted individually (grab the blue vertical line between columns and drag it to a suitable point)

Known behaviours:
1. The information in each cell can be hidden by resizing the columns
1. The total width of the table can 'spill over' to the right, when all columns are expanded and the information in them is too wide.

**Comment by ErwinKomen** [comment]
As for known behaviour (2): the better solution here may be to _not allow_ spilling over. That is to say, when the user presses a column that should be expanded, but it would spill over: not expand it (or expand it to the maximum that it can).

**Comment by MennaRempt** [comment]
I can't expand the columns (or even click on them) when I use Google Chrome (on Linux (Kubuntu 18.04)), but it does work when I use firefox.

**Comment by MennaRempt** [comment]
Also, the "shelfmark" column should contain City+Library+Shelfmark. (e.g. "Cologny, Fondation Martin Bodmer, Cod. Bodmer 128" rather than just "Cod. Bodmer 128")

**Comment by ErwinKomen** [comment]
1. **Shelfmark**: I changed that back to what it was earlier (city + lib + shelfmark). 
1. **Browswer compatibility**: it does work on **Google Chrome** under Windows 10. Did you do Ctrl+F5 to refresh the browser?

**Comment by MennaRempt** [comment]
Works now!
