### ISSUE TITLE
SSG detail view: order editions chronologically

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#229]
When a Sermon, Gold Sermon or Super Sermon Gold has multiple editions, they should be chronologically organized, the most recent first.

**Comment by ErwinKomen** [comment]
Action: review and sort out the Edition order for SSG.
Then double check and implement:

1. `S` details view:
1. `SG` details view:
1. `SSG` details view:

**Comment by ErwinKomen** [comment]
Notes:
1. Edition order (and showing) is determined in `get_editions_markdown()`, which is a method to S, SG and SSG
1. Right now the order is by 'reference__short'
1. The table `Litref` does _not_ contain the publication year in a separate year
    1. It is part of the 'short' field in brackets
    1. It is structurally part of the 'data' field (a JSON stringified)

So actions:
1. **Model**: extend `Litref` with a `year` field that should contain the year as a number - _ok_
1. Code and execute a _data migration_ where the dates are derived straight from the `data` field - _ok_
1. Whenever the field `short` is calculated, the field `date` should also be calculated
    1. That is done in `Litref`, method `read_zotero()` - _Okay I added this_

**Comment by ErwinKomen** [comment]
Implementation:

1. `SSG` details view:
1. `SG` details view:
1. `S` details view:

**Comment by ErwinKomen** [comment]
Okay,the above works. There's one thing I notice, however, which is not necessarily related to the publication year. When there are multiple editions, more are shown than should be shown.
E.g. https://passim.rich.ru.nl/sermon/details/54669/ shows 7 editions, while it's only 2 different editions. 

The problem here is that these editions _are_ different , because the `sermon_gold` field from `EdirefSG` differs. But they are the same, in the sense that the `reference` field and the `pages` field of them are equal.

**Comment by ErwinKomen** [comment]
Okay, I made sure that the list of editions only contains different ones.
(and they are ordered chronologically now)
