### ISSUE TITLE
SG: cannot be opened or removed after SSG removal

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#230]
When a SSG is removed, the SG's in the equality set must remain stored in the database (for possibly a new SSG). But the editors should also be able to open them in order to remove them if necessary. According to Menna this is not possible right now. This should be checked out

**Comment by ErwinKomen** [comment]
SSG and SG removal:
1. When an SSG is removed, the SGs are **not** removed.
1. Accessing them:
    1. Remember their detail link id (URL)
    1. Search them in the SG listview through their Gryson or other characteristics

When SGs need to be removed with an SSG:
1. Open de SSG
1. One-by-one open de SGs to be removed in other tabs of your browser
1. Remove the SGs that need to be removed
1. Remove the SSG

I double checked this, but there is one related observation.
When an SSG is removed, its SGs remain there, but the details view of the SG shows quite a few additional SGs in the 'together with' set. This is probably because the `equal` field has now received value `None`. But this behaviour is undesirable.
TODO: when the `equal` field of an SG equals `None`, the SG details view must **never** show any contents in the 'TOgether with' field.

**Comment by ErwinKomen** [comment]
This has been completely resoled now
