### ISSUE TITLE
M, S and SSG detail view: editions and Clavis/Gryson codes cannot be imported, no link indications

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#235]
Currently, it is not possible to import information (editions and Clavis/Gryson codes) from a linked SSG to a Sermon manifestation. There is also no possibility to add editions manually after they are linked to a SSG.  

After a link with a SSG, there is no indication in the Manuscript contents in the Manuscript detail view that a Sermon is linked to a SSG. The Manuscript is also not listed in the SSG detail view. 

The solution that Menna suggests is to automatically copy the editions and Clavis/Gryson codes after a Sermon manifestation is linked to a SSG with an _equals_-link.  In case of a _partial_-link, the editor  would have to copy the editions and codes manually. 

An example: https://passim.rich.ru.nl/manuscript/details/1133

and: [insert example SSG that belongs to the S in the M, have asked Menna]

> Menna: "er is al een issue voor de mogelijkheid om incipit en explicit te kopiëren van een SSG (#205), dit moet niet automatisch gebeuren."
> 
> Het gaat om zowel oude als nieuwe manifestaties. Bij veel oude manifestaties zijn de edities/codes al wel toegevoegd omdat met het oude systeem de SG-informatie gekopiëerd kon worden, maar dat is nu niet meer mogelijk, dus nu kunnen er alleen handmatig codes worden toegevoegd, bij alle manifestaties (en geen edities).

**Comment by ErwinKomen** [comment]
Menna writes:
> Currently, it is not possible to import information (editions and Clavis/Gryson codes) from a linked SSG to a Sermon manifestation. There is also no possibility to add editions manually after they are linked to a SSG.

It's correct that it is no _manual_ edition adding to Sermon manifestations. That's by design. If that needs doing, please discuss with Shari and make a separate issue.
**Note** however: two pieces of information are _automatically_ shown as soon as a sermon has an 'equal' link to a SSG:
1. The Gryson/Clavis (auto) field shows all Gryson/Clavis of the items in the same equality set. If there's something missing here, make a separate issue, because this should be the desired behaviour.
1. The editions belonging to the items in the equality set are shown. Again, if this appears to be not the case, make this into a separate issue.

**Comment by ErwinKomen** [comment]
Menna writes:
> After a link with a SSG, there is no indication in the Manuscript contents in the Manuscript detail view that a Sermon is linked to a SSG. The Manuscript is also not listed in the SSG detail view.

This is a completely different issue.
1. The information from the equality set becomes visible within the Sermon details view
    1. DOuble checked edition information: was wrong, repaired. It now shows all the editions belonging to the SGs that are part of the same equality sets linked with 'equal' to the sermon.
    1. Double checked signature info: was wrong (used the old S-SG link information). Repaired.
1. The sermon and its manuscript are shown in the details view of the SSG
    1. Double checked detail view `EqualGoldDetails`. This also still assumes the ancient link between S - SG. Repaired.

So: this part of the issue is now resolved

**Comment by ErwinKomen** [comment]
In sum, I think the problems raised in this issue were due to the wrong links being made available automatically. So I think this is now resolved.
Except for one thing: 

> After a link with a SSG, there is no indication in the Manuscript contents in the Manuscript detail view that a Sermon is linked to a SSG. 

**Question**: Does there need to be an indication in a Sermon that is shown in the Manuscript Detail view, that this sermon is linked to a SSG?

**Comment by shariboodts** [comment]
Question: Does there need to be an indication in a Sermon that is shown in the Manuscript Detail view, that this sermon is linked to a SSG?

This does seem useful to me, because it gives a user an immediate idea of which sermon manifestations in a manuscript have been identified with an SSG and are properly linked. We could use a symbol for this? I've gone over a few possible symbols, but nothing came to mind that is unambiguous (infinity-symbol would imply a hyperlink). Do you have ideas for an appropriate symbol?

**Comment by ErwinKomen** [comment]
We usually get our symbols from Bootstrap 3 Glyphicon: https://getbootstrap.com/docs/3.3/components/

**Comment by MennaRempt** [comment]
It's currently indicated with a yellow "G", in some manuscripts, at least, e.g. https://passim.rich.ru.nl/manuscript/details/1180/. I'm not sure why it isn't indicated for all manuscripts, but I think the difference is between the manuscripts linked before the SSG update and those linked after the update. (compare https://passim.rich.ru.nl/manuscript/details/1134/)

**Comment by ErwinKomen** [comment]
No no no, the yellow 'G' stands for **Gold** sermon.

What about 'glyphicon-eject', pointing 'upwards'?

**Comment by shariboodts** [comment]
Glyphicon-eject's meaning is not immediately clear to me in this context. And chances are we will change SSG's name for the final database, so maybe the glyphicon-link is still the best option? That or perhaps the 'connection' symbol (example: https://www.freepik.com/free-icon/connection-symbol_732411.htm) to show that this manifestation is 'connected' to the 'network' of the database (also not perfect...).

**Comment by ErwinKomen** [comment]
Okay, done.
