### ISSUE TITLE
SSG: moved SSG can still be linked to manifestation

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#244]
Iris: "SSG's die 'verhuisd' zijn naar een nieuwe PASSIM code, zijn in de oude versie nog steeds vindbaar, bewerkbaar en te linken aan manifestaties. Zie bijvoorbeeld PS-AU s 213 (si quis sollicitus); als ik deze probeer te linken aan een manifestatie, vind ik 'm twee keer. Klopt het dat de oude eigenlijk niet meer zichtbaar of zeker niet bewerkbaar zou moeten zijn?" 

De oude SSG moet inderdaad als het ware "inactief" zijn, en dus niet meer bewerkbaar of aan manifestaties te linken. 

(PS-AU s 213 = PASSIM 001.0188 > 051.0195)

**Comment by ErwinKomen** [comment]
Iris and Menna, this is linked to what is described about the SSG field **moved** in issues #170, #174.

This is what happens with an SSG for which the author gets changed:
1. Suppose the 'original' SSG has id **50**
1. A copy is made of the current version of the SSG (with the 'original' author link). Let's say it gets id **60**
    1. The field **moved** of this copy (of **60**) points to the 'original' SSG (with id **50**)
1. The field **author** for the 'original' SSG (id **50** changes into the new author
1. Since the original SSG has retained its original id (that is, **50**), anything pointing to it (e.g. SG instances) and automatically 
attached to it through these SG links (editions, keywords) has _not_ changed at all.

So this is the expected behaviour:
1. It is still possible to find SSGs that are no longer valid right now. They can be recognized, though, because their 'moved' field has a value.
1. It is still possible to view and edit these 'moved' SSGs

Actions that I take away from the description that need attention:
1. SSGs with field 'moved' filled in may not show up for link-selection
1. SSGs with field 'moved' filled in may should be non-editable, i.e. **view-only**

**Comment by ErwinKomen** [comment]
Action implementation:
1. Added `moved__isnull=True` filter in forms.py to the relevant places
1.

**Comment by ErwinKomen** [comment]
Should be okay now.
