### ISSUE TITLE
PD collection: listview sorting

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#265]
See issue #259 point 11:
> [The] List view for a PD of manuscripts should have the possibility to sort the manuscripts: 
> - alphabetically using city + library + shelfmark (this is default), 
> - but also sorting chronologically. 
>
> The automatic numbering of the items just reorders depending on the sorting system chosen (it is meant to help the user navigate his or her dataset, the number is not .

**EK**: 
- this seems to contradict issue #262, which says that each item in a collection should have its own number
- the last sentence above (`...the number is not`) is unfinished, so it is unclear what is meant here
- besides: sorting the manuscripts in a PD (or HC) can already by done by using the **Manuscript Listview**, filtering it on the correct PD (or HC) and sorting there.

**Comment by MennaRempt** [comment]
I think there doesn't have to be an automatic numbering when resorting, rather that the manually assigned numbering should be kept intact. So disregard the last sentence. (Unless @shariboodts meant something different with the numbering?)

**Comment by shariboodts** [comment]
Indeed, the last sentence may be disregarded. Is it intuitive for users to navigate their PD's using the Manuscript Listview, rather than doing any sorting or navigating in their personal user environment? In their personal user environment, users can not only navigate, but also at the same time edit their PD's, which they cannot in the Manuscript Listview, so I do think it is useful to have navigating options in the personal user environment. That being said, the numbering of the items in the PD can stay fixed.

**Comment by ErwinKomen** [comment]
Implementation notes:
- Make sure that integers are sorted as integers, and not as string

**Comment by ErwinKomen** [comment]
Okay, sorting works. Note that sorting is **not** saved.
