### ISSUE TITLE
Manuscript: import from excel

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#282]
The possibility to import a manuscript from an excel file with:
1. metadata over het manuscript (manuscript details)
1. de lijst met manifestaties (and sermon details for each manifestation) 
1. de lijst met SSG’s corresponderend met de manifestaties (if possible with automatic linking, otherwise as a note?) 
1. bibliografie op basis waarvan de gebruiker/editor de beschrijving gemaakt heeft.

**Comment by ErwinKomen** [comment]
Actions and thoughts...
1. Add **excel** import method to Manuscript listview
    1. This uses `uploads`, which is fed from reader/views.py
    1. But I want to add the Excel import method from a different location: do that in method `initializations()`
1. Add a view `ManuscriptUploadExcel` that extends `ReaderImport` to actually import the Excel document(s)

**Comment by ErwinKomen** [comment]
Okay, this is working now. I have tried to evaluate the different functionality parts. But the user will need to attempt this and see where errors may still occur

**Comment by MennaRempt** [comment]
Current issues: 

- SSG linking: I can't get automatic linking to SSGs to work when importing a manuscript (using the exact syntax as in the downloaded manuscripts and your example manuscript: e.g. ["PASSIM 001.0002"]) 
- The information about the failed SSG does not appear in the 'note' field.
- manual Gryson/Clavis codes seem to always appear as 'other codes', rather than as Gryson or Clavis codes. Is it possible to make the database automatically parse it as either Gryson or Clavis (based on existing examples or if I give a list of possible prefixes for Clavis codes)? Otherwise users have to check and fix them after uploading (this wouldn't be a big problem since users have to check imported manuscripts anyway)

**Comment by ErwinKomen** [comment]
As for the issues above:
1. SSG linking: I fixed this. The application is able to deal with ["", ""] sequences as well as those without quotation marks and square brackets (provided they don't have comma's for other purposes). It was because of this generality that one of the two types (the ["", ""] one) had been kind of 'switched off'. I expect there should also have been problems importing similar lists for user keywords, datasets and manuasl signatures (except that these things don't occur very frequently anyway).
2. Failed SSG info: the program didn't 'get' the information, so wasn't able to see that it failed processing it. This should now work better.
3. Processing of Gryson/Clavis: THis is weird. Please give me an example. RIght now the code should be 'clever': interpret unknown signatures by default as Gryson, but if they contain CPPM, interpret them as Clavis. And if the signature is already known, then copy the current interpretation (Gr/Cl/Ot).
