### ISSUE TITLE
PASSIM code is not stable

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#295]
The PASSIM code seems to change whenever a SSG is edited, without changing the elevated SG. Previous codes then no longer exist in the database.

**Comment by ErwinKomen** [comment]
Thanks for noticing. This was a nasty bug. But it's fixed now.

The problem was that the `number` field (that holds the number of the SSG for one particular author) was not properly passed on and on in the SSG details view. So since it wasn't there, it was reset to None during saving, and since the saving routine detected this, it issued a new number for it.

I've repaired this now, and made sure that the `number` is properly recovered from the PASSIM code, should anything go wrong.

I'm sorry to say that some of the PASSIM codes have gotten changed.
Should I repair these manually?

| Passim Code now | Suggested correction |
| === | === |
| `PASSIM 004.0191` | `PASSIM 004.0010` |
