### ISSUE TITLE
Search: extend

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#33]
Extend the search functionality:
1. Het moet mogelijk zijn om te zoeken op 'alles' (in de database) binnen een bepaalde tijdrange.
1. Het moet ook mogelijk zijn om met behulp van (preken)collecties te zoeken:
    1. alle handschriften verbonden aan die (preken)collectie
1. Terminologie:
    1. Zoeken: door de hele database zoeken naar resultaten (toevoegen aan, afhalen van het 'mandje')
    1. Filteren: de gevonden zoekresultaten filteren
        1. Bijvoorbeeld: ik wil enkel de manuscripten overhouden waar minstens 2 (3, 4…alle) preken van mijn virtuele collectie preken inzitten
1. Zoek op frequentie:
    1. Geef alle preken uit de database die maar 1 (of 2, of 3 etc) keer voorkomen 
    1. SB: Het moet ook mogelijk zijn om voor de database als geheel een zoekopdracht uit te voeren waarbij je de preken vindt die slechts in 1 manuscript in de database zitten – unieke preken dus, die slechts 1 keer voorkomen in de ganse database. Anderzijds moet je ook de preken kunnen vinden die het meest populair zijn en die dus in de meeste handschriften voorkomen. Ik weet nog niet precies waar deze zoekfunctie moet ondergebracht worden.

**Comment by ErwinKomen** [comment]
Search for 'everything'
---

Search by using (sermon)collections:
---
This is already possible from all different angles

Terminology
---

**Comment by ErwinKomen** [comment]
Questions for the team
---
1. What more is needed where date (ranges) are included? (i.e. related to (1) above)
1. Do I have the right definition of "frequency of occurrance" in (4)?

**Comment by MennaRempt** [comment]
**1. What more is needed where date (ranges) are included? (i.e. related to (1) above)**
Date range is always connected to manuscripts, so if it's possible to search for date range everywhere where you can search using manuscript filters that seems fine to me. The only possible extension I can think of is being able to filter SSGs based on the dates of the associated manuscripts. 

**2. What exactly is the request for (3) 'Terminology'?** 
I think there is no request, but rather a clarification of the way in which "search" and "filter" are used.

**3. Do I have the right definition of "frequency of occurrance" in (4)?**
I think so, yes. Perhaps "preken" in this instance might also refer to SSG, but @shariboodts would probably know better what exactly was meant by this (since this issue is from before I started).

**Comment by ErwinKomen** [comment]
# Do I have the right definition of "frequency of occurrance" in (4)?
As for (3), Shari and Erwin talked about this too, and the frequency-of-occurrance basically is the _number of sermon (manifestation)s belonging to one SSG_. This is contra the more difficult (second order) definition above.
