### ISSUE TITLE
Search: unique URL

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#354]
Create a unique URL for each search query, with the applied filters saved.

**Comment by ErwinKomen** [comment]
Different possible approaches:
1. Allow searching in general using GET (on top of POST)
2. Store each search and allow re-searching using the search's number (id)

Option (2) is best, because:
- Storing searches (per user) is already interesting
- We could have a separate URL for a numbered search, i.e. no need to use GET queries for it
