### ISSUE TITLE
MS bug: mark as approved

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#364]
MS. [1354](https://passim.rich.ru.nl/manuscript/details/1354/) (Engelberg Stiftsbiliothek Cod. 47) cannot be marked as approved (automatically changes back to 'edited').

**Comment by MennaRempt** [comment]
Update: this seems to be the case for all manuscripts

**Comment by ErwinKomen** [comment]
This was due to the switch to `Codico`. 
Some fields (e.g. the `name` of a Manuscript) were still in the `stype_edi_fields` variable for the Edit view.
THis meant that 'changes' (not real changes, because these are stale fields) rippled through into `passim_action_add()`, where they caused the `stype` to be put to STYPE_EDITED again.

Fixed by updating the  `stype_edi_fields` variable for ManuscrptEdit
