### ISSUE TITLE
Filter: bible reference

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#418]
Filtering manuscripts or sermons on Bible Reference does not work: in both cases, it yields the full list of results.

**Comment by ErwinKomen** [comment]
The problem was in `make_search_list()` (basic app). That interpreted `$dummy` wrongly.
Then later there were some additional problems.
I solved hem by adapting the code in `BasicList`, `get_queryset()`
I also managed to speed up the execution a bit by determining the length of the results differently:
```python
        # Determine the length
        self.entrycount = 0 if qs is None else qs.count()   # len(qs)
```
