### ISSUE TITLE
Bibliography: general

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#424]
1. Headings: "edition references" should be changed to "Editions"; "Literature references" should be changed to "Literature"
2. Add a list "Online resources" (see issue #425)
3. Add a hyperlinked table of contents on the top of the bibliography page (links to go immediately to 'Editions', 'Literature' or 'Online Resources' without having to scroll down)
3. For the alphabetization of author names, accented letters not be treated differently from their unaccented equivalents; e.g. Étaix is now at the bottom of the list, while it should be with the other 'E-'names.
4. Clicking on a bibliographical reference on a MS/S/SG/SSG etc. page redirects the user to the reference on the bibliography page; however, the reference ends up just 'above' the screen, so that the user has to scroll up to see it. The reference should be either the first item visible on the screen, or in the middle of the screen

**Comment by ThijsRU** [comment]
Maybe the Bibliography section needs to be changed to match the rest of the list views.

**Comment by ThijsRU** [comment]
1. Headings: "edition references" should be changed to "Editions"; "Literature references" should be changed to "Literature" 

DONE 

2. Add a list "Online resources" (see issue https://github.com/ErwinKomen/RU-passim/issues/425)

TH: Separate issue #425 

3. Add a hyperlinked table of contents on the top of the bibliography page (links to go immediately to 'Editions', 'Literature' or 'Online Resources' without having to scroll down)

TH:

4. For the alphabetization of author names, accented letters not be treated differently from their unaccented equivalents; e.g. Étaix is now at the bottom of the list, while it should be with the other 'E-'names.

TH: the querysets are ordered using the 'short' field, when using 'full' field: it looks much better but "Étaix" is because of the accent still overlooked. 

5. Clicking on a bibliographical reference on a MS/S/SG/SSG etc. page redirects the user to the reference on the bibliography page; however, the reference ends up just 'above' the screen, so that the user has to scroll up to see it. The reference should be either the first item visible on the screen, or in the middle of the screen

TH: this should be technically possible for the literature and editions but I do not think that is will be possible with the online resources records since there will be no direct link between the full URL with a manuscript and the "general" URL and name combination in the Online resources list, assuming we implement issue #425 as is suggested right now.

**Comment by ThijsRU** [comment]
This is issue is ready. The sorting will be taken care of in issue #541.
