### ISSUE TITLE
Bibliograpy: online resources

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#425]
Create a list of online resources:

1. automatically compile a list of all URLs quoted in PASSIM under external links, in alphabetical order
2. Menna will then manually create a shortlist of the names and general URLs of these sites
3. Add this shortlist as the online resources on the bibliography page

**Comment by ThijsRU** [comment]
- locations of URLs in the PASSIM application (name model and field):

  - Ftextlink, url
  - Manuscript, url
  - ManuscriptExt, url
  - Collection, url
  - SourceInfo, url (relevant?)

Questions: 
 - Will this proces have to be repeated?
 - What is the end result?
 - Is it possible to generate a list on the fly?
 - Clicking on a URL should lead to the general URL under Online sources in the Bibliography
- literature_list.html, add new table Online resources

- LitrefListView, create new queryset, add context

**Comment by ThijsRU** [comment]
List with names and URLs is ready for import, via adaptations.py makes more sense than directly in the template. This way the process can be repeated more easily when necessary.

- store sheet in URLs_16032022.xlsx as csv: online_sources.csv DONE
- create new model class OnlineSources DONE
- via listview manuscripts DONE
- ok, allkinds of issues with characters in csv, save as csv utf-8, make sure there is nothing in the file after the last record DONE
- still issues with characters, view import XMLs, encoding = utf8 DONE
- LitRefView modified, literature_list template adapted DONE
- e-codices not sorted properly
- csv needs to be copied to the server
- separate issue:  create views detail, edit and list in order to add new URLs later on

**Comment by ThijsRU** [comment]
This is done, the sorting will be taken care of in issue #541.
