### ISSUE TITLE
Search filters: basic

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#445]
For all pages with search filters:

- The 'filter' symbol is not very clear; change it to a different symbol (magnifying glass?) or just a button with text "filter", and increase the size.
- The search filter should be automatically expanded (as they would be when clicking the filter symbol, not completely)

**Comment by ThijsRU** [comment]
- symbol is now magnifying glass (class="glyphicon glyphicon-search instead of -filter")
- also changed in "filter_help.html"
- 
- increase size: also other buttons, btn btn-xs -- > btn btn-s, is this working
- make sure the buttons stay on one level  


- The search filter should be automatically expanded (as they would be when clicking the filter symbol, not completely)
-  ??

**Comment by ThijsRU** [comment]
Done

**Comment by MennaRempt** [comment]
The search filter symbol is still given as the old filter instead of the new magnifying glass in the contextual help pop-up (accessible with the question mark).

**Comment by ThijsRU** [comment]
remove filter_help.html out of seeker, delete all references to this template, this is already taken care of in basic

template_help = "seeker/filter_help.html" --> delete in seeker/views.py  (S, M, C, SG, EG, EGL)

to do: delete template from seeker

**Comment by ThijsRU** [comment]
This issue can be closed.
