### ISSUE TITLE
Basket: remove duplicates

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#465]
Currently it is possible to add the same item to a basket multiple times; it will also be shown in the basket listview multiple times. There should be an option to easily remove all duplicate items from the basket.

**Comment by ErwinKomen** [comment]
I would say that a basket should **never** contain duplicates! Good issue...

**Comment by ErwinKomen** [comment]
#### Implementation
All basket operations are handled in view `BasketUpdate`.
There are like 8 possible basket operations, and two of these are relevant for the current issue: `create` and `add`.
Possibly only the latter is relevant, since any search will only yield distinct results (i.e. create only gets unique results).

Indeed, the current response to `add` is:
```python
                    elif search_count > 0  and operation == "add":
                        # Add
                        with transaction.atomic():
                            for item in search_id:
                                kwargs["{}_id".format(self.s_field)] = item
                                self.clsBasket.objects.create(**kwargs)
```

**Comment by ErwinKomen** [comment]
Solved.
