### ISSUE TITLE
MS creation bug

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#503]
It's currently not possible to add new manuscripts; after clicking the "add a new manuscript" button, the following page is shown: 

![image](https://user-images.githubusercontent.com/59916079/148908336-d35b0007-29b0-487b-bb6e-6c668653497e.png)
 
The edit button does not do anything on this page, and no new manuscript can be found by going back to the MS listview.

**Comment by ErwinKomen** [comment]
The problem was related to issue #479 
I'd been doing default project assignment there, but I'd put it in the `before_save()` method of `ManuscriptDetails`.
That's okay for existing manuscripts, but not for new ones, because those don't have an `id` value yet before being saved.
I moved the code to the `after_save()` method, and now it works again (including default project assignment). I checked.
