### ISSUE TITLE
HUWA import: opera as AF

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#558]
The following types of opera have to be imported as AFs:

immediately possible to import:
- opera with multiple links to inhalt and no number in abk that have been assigned a Gryson/Clavis-code in the "opera_passim" document.
- opera with multiple links to inhalt and a number in abk that have been assigned a Gryson/Clavis-code in the "opera_passim" document. 
- opera with no links to inhalt that have been assigned a Gryson/Clavis-code in the "opera_passim" document.

preliminary steps required:
- opera with multiple links to inhalt and a number in abk that have not been assigned a Gryson/Clavis-code, of which the abk corresponds to a code on the sermo codes concordance ("HUWA sermo codes"). 
    For these, a Gryson and/or Clavis-code can be constructed based on the concordance, after which they can be imported.
    All new AFs created through this list should get both '[HUWA/CSEL](https://passim.rich.ru.nl/project/details/7/)' label and "PASSIM".

To limit doubles, based on the Gryson/Clavis code:
 - If match between HUWA-opus and PASSIM AF is 1 to 1, can be imported without further checks needed.
- If match between HUWA-opus and PASSIM AF is 1 to 2 (or more), manual decision is necessary.
- If match between HUWA-opus and PASSIM AF is 2 (or more) to 1, manual decision is necessary.

To import HUWA opera for which a PASSIM AF already exists, import the HUWA opera as a new SG to be added to the PASSIM AF with keyword 'HUWA import'. The AFs have to be assigned the '[HUWA/CSEL](https://passim.rich.ru.nl/project/details/7/)' project label.

**Comment by MennaRempt** [comment]
NB: opera that are imported as AFs have to remain linked to the HUWA ID, so that they can be linked to their manifestations in manuscripts when the HUWA manuscripts and manifestations are imported.

**Comment by ErwinKomen** [comment]
This issue is a bit problematic, because it is not clear which specific part in the following table is being addressed. Is it just the `ssg11ef` part or also `ssg1_n`, or does it even includes the `zero_links` cells from column `opera_ssg_1_1`?

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/u459154/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/u459154/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Aantal   van opera | Kolomlabels |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
Rijlabels | opera_ssg_0_0 | opera_ssg_0_n | opera_ssg_1_0 | opera_ssg_1_1 | opera_ssg_1_n | opera_ssg_n_1 | (leeg) | Eindtotaal
ssgmE: empty inc or exp | 1999 |   | 266 | 80 | 136 | 31 |   | 2512
many_links_ABK_num | 83 |   | 27 | 14 | 22 | 3 |   | 149
many_links_ABK_txt | 304 |   | 17 | 5 |   | 4 |   | 330
one_link | 1446 |   | 201 | 45 | 87 | 14 |   | 1793
zero_links | 166 |   | 21 | 16 | 27 | 10 |   | 240
ssgmF: full inc/exp match | 3 |   | 4 | 4 | 10 | 3 |   | 24
many_links_ABK_num | 3 |   |   |   | 6 | 2 |   | 11
many_links_ABK_txt |   |   |   | 1 |   |   |   | 1
one_link |   |   | 4 | 1 | 4 | 1 |   | 10
zero_links |   |   |   | 2 |   |   |   | 2
ssgmN: no inc/exp match | 4886 | 19 | 1266 | 461 | 1503 | 419 |   | 8554
many_links_ABK_num | 609 | 8 | 547 | 236 | 755 | 253 |   | 2408
many_links_ABK_txt | 386 | 1 | 170 | 21 | 20 | 26 |   | 624
one_link | 3057 | 7 | 340 | 144 | 545 | 96 |   | 4189
zero_links | 834 | 3 | 209 | 60 | 183 | 44 |   | 1333
(leeg) |   |   |   |   |   |   |   |  
(leeg) |   |   |   |   |   |   |   |  
Eindtotaal | 6888 | 19 | 1536 | 545 | 1649 | 453 |   | 11090
  |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |  
Subset | Description |   |   | Aantal | Action | Status |   |  
all_zero | all 'zero_links' |   |   | 1575 | CW: investigate | subset made |   |  
ssg00_m | Column 'opera_ssg_0_0' and   'many_links*' | 1385 | subset | subset made |   |  
ssg00_o | Column 'opera_ssg_0_0' and   'one_link' | 4503 | subset | subset made |   |  
ssg0n | Column 'opera_ssg_0_n' |   | 16 | import corrected | MR corrected, EK: clarify +import
ssg11ef | Column 'opera_ssg_1_1' and ssgmE /   ssgmF | 66 | subset + import | subset made + see issue #534
ssg11_n | Column 'opera_ssg_1_1' and ssgmN | 401 | subset | subset made |   |  
ssg1n | Column 'opera_ssg_1_n' |   | 1439 | subset | subset made |   |  
ssgn1 | Column 'opera_ssg_n_1' |   | 399 | subset | subset made |   |  
ssg10_f | Column 'opera_ssg_1_0' and ssgmF | 4 | Import as AF |   |   |  
ssg10_nz | Column 'opera_ssg_1_0' and not   zero_links | 1302 | Import as AF |   |   |  



</body>

</html>

**Comment by ErwinKomen** [comment]
This has now been overtaken by the instructions to import first, and correct the imported materials later.
