### ISSUE TITLE
Linktypes: delete old types

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#634]
See issue #336; I have now gone through the AFs mentioned in the comment there and deleted/changed the old linktypes to the new ones. 

Please remove the old linktypes from the list of main linktypes (similar_to; unspecified; uses).

**Comment by ErwinKomen** [comment]
This issue is from over a year ago, and some 'uses' and 'similar_to' have crept in.

1. Please update the AF-to-AFlinks that now have linktypes:
   1. 'unspecified' (6033-to-2140,  725-to-1569)
   2. 'uses' (from AF 7264 to: 3611, 4207, 2656, 4208)

Having done that, contact me (EK) to 'remove the old linktypes from the list' immediately

**Comment by ErwinKomen** [comment]
Okay, I have now double-checked and removed three items from FieldChoice `seeker.linktype`

![image](https://github.com/ErwinKomen/RU-passim/assets/11887269/5b0c77f7-fbf7-470c-af21-b0aad20fe999)
