### ISSUE TITLE
BUG - Search for AF filters in manuscript search filters

### ISSUE THREAD

**Issue by shariboodts** [ErwinKomen/RU-passim#763]
When entering data in the field Manuscripts > Authority files > author/incipit/explicit/gryson the application gives back that there are no results, when we know that there are indeed results. This seems to be a bug.

**Comment by Irisdenis** [comment]
The problem in searching via author/incipit/explicit seems to have fixed itself (I don't know how, maybe it was just a temporary thing).

For Gryson/Clavis, the problem remains: if entering a specific Gryson/Clavis code, or selecting it from the drop down menu in the upper field (e.g. PS-AU s 121a), there are no results (when there should be). A search using wildcards is also problematic: *AU s* gives only 27 results (which is impossible).

The second search option ('select multiple signatures') works as it should, apparently. 

**Note for user manual:** there can be a discrepancy between the number of manuscripts displayed for a given AF(e.g. CAE s 78 > 10) and the number of manifestations linked to the same AF (11, in this case); this, I think, can be explained because the sermon occurs twice in the same manuscript (which is counted as 1 manuscript).

**Comment by ErwinKomen** [comment]
### Searching for Gryson/Clavis
1. Searching for `PS-AU 2 121a` yields 17 manuscripts in the Manuscript list view
1. Double checking the results:
    1. Signature is 1411, G = 929, Equal = 801
    2. Table `SermonDescrEqual`: 22 manuscripts. All differing, but no manu features double checked.
